### PR TITLE
Minor style issue [ fixed ]

### PR DESCRIPTION
**Pull request by knakul853**
there was unnecessary spaces between the different includes and between different spaces.
In this PR I tried to fix that.

### CODE REVIEW

**Comment by birm** [comment]
This PR looks like it covers more than just style/grammar changes to models.

**Comment by birm** [comment]
looking slightly closer, many of the commits are common with #39. If possible, you should consider having each PR branch contain only the new commits related to the PR. As is, we can't merge your style change commit 4dd8ab without including your cmake features. I think this is because your forked your style branch off of your master branch, which already contained your cmake commits.

**Comment by knakul853** [comment]
Hey this is not intended only the last commit was intended for this PR let me close this I will reopen this

**Comment by knakul853** [comment]
Hey this is not intended only the last commit was intended for this PR let me close this I will reopen this

**Pull request closed without merging**
