### PR TITLE
Add MNIST Dataset

### PR DESCRIPTION
**Pull request by ShikharJ**

### CODE REVIEW

**Comment by zoq** [comment]
What do you think, does it make sense to put the dataset into an extra directory?

**Comment by ShikharJ** [comment]
@zoq It is already inside the additional directory (`GANs/`).

**Comment by zoq** [comment]
Right, I was thinking about a directory that is in the root folder. I guess it might be easier to see if a dataset is already available if there is a single place. Not sure someone will look into the GAN folder if I run a Variational Autoencoder.

**Comment by ShikharJ** [comment]
@zoq Can this be merged now?

**Comment by zoq** [comment]
Last really picky comment, do you mind to use ``data`` instead of ``Data``, I like to be consistent with the mlpack codebase here.

**Comment by ShikharJ** [comment]
@zoq Done.

**Comment by ShikharJ** [comment]
@zoq Can we merge this now?

**Comment by zoq** [comment]
Thanks, easy merge.

**Pull request merged**
