### PR TITLE
Image Dataloader Documentation

### PR DESCRIPTION
**Pull request by kartikdutt18**
Hey everyone, This is the documentation for image dataloader. I'll be updating the wiki in the forked repo shortly and will post the link here. Kindly let me know what you think. Till then, I'll get started with DarkNet 19. Thanks.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
The updated wiki page can be found here.

**Comment by KimSangYeon-DGU** [comment]
@kartikdutt18 Can you update the wiki like this?
```
dataset : Dataset on which augmentation will be applied.
datapointWidth : Width of a single data point i.e. Since each column represents a separate data point.
datapointHeight : Height of a single data point.
datapointDepth : Depth of a single data point. For 2-dimensional data point, set it to 1. Defaults to 1.
```

**Comment by kartikdutt18** [comment]
Ahh, Makes sense. Sorry I missed that. Done.

**Comment by KimSangYeon-DGU** [comment]
@kartikdutt18 Thanks for the nice documentation 👍

**Comment by kartikdutt18** [comment]
Thanks a lot @KimSangYeon-DGU for the reviews. I think I can change the wiki now too.

**Pull request merged**
