### PR TITLE
Initial ci config to set up the azure pipeline.

### PR DESCRIPTION
**Pull request by zoq**
Just here to set up the azure pipeline, the actual config file is part of: https://github.com/mlpack/models/pull/3.

### CODE REVIEW

**Comment by rcurtin** [comment]
Should it have fired off an Azure build with the simple script?  Or maybe there is additional setup needed?

**Comment by zoq** [comment]
No, once this is merged I can configure the pipeline to use the config file in the master branch, this is really just a dummy config.

**Comment by birm** [comment]
Let's do this!

**Comment by zoq** [comment]
Thanks, pipeline configured.

**Pull request merged**
