### PR TITLE
use ensmallen for the optimization step

### PR DESCRIPTION
**Pull request by zoq**
Since mlpack now uses ensmallen, we have to update the code here as well.

### CODE REVIEW

**Comment by rcurtin** [comment]
I see, I think the issue is that mlpack does not install ensmallen if it needed to download it.  I can put this on my list for tomorrow unless you want to handle it.

**Comment by rcurtin** [comment]
> on my list for tomorrow

for some definition of tomorrow... here's a patch: https://gist.github.com/rcurtin/1121ccf1bb55cfab9299285d94e7c527

**Comment by zoq** [comment]
Sorry for the delay, wasn't my plan to beat your "tomorrow".

**Comment by Soonmok** [comment]
Should i remove my pull request [added gan #22] and add ensmallen here? ..

**Comment by zoq** [comment]
You are right, it just runs the default configuration, perhaps we should disable it for now.

**Comment by rcurtin** [comment]
Sounds good; we can disable it if you want, but I also remember there is another PR open to fix it.  So it doesn't make such a huge difference to me either way. :+1:

**Pull request merged**
