### PR TITLE
Added ZFNet model

### PR DESCRIPTION
**Pull request by prince776**
I've added ZFNet model with the same structure as created in #3.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
Hey @prince776, wasn't @codeboy5 working on this. Great addition though but It might be a while before we add this model. I think the first step would be setting up this repo before actually start adding other models. Thanks 👍.
There are lot of changes in cmake, data loader and maybe model. There will also be a testing unit that I'll be setting up. So you would have to sit tight for a couple of days. Thanks again.

**Comment by codeboy5** [comment]
Hi @kartikdutt18.
I've already done the implementation but didn't add a PR due to the restructuring going on, was waiting for it to be completed.
I opened the issue a week ago.
https://github.com/mlpack/examples/issues/63

**Comment by prince776** [comment]
Oh right, I just saw he was working on it. What should I do then?

Also yes you're right, restructuring and setting up the repo should be done first. I'll try to help with it too.

**Comment by prince776** [comment]
> Hi @kartikdutt18.
> I've already done the implementation but didn't add a PR due to the restructuring going on, was waiting for it to be completed.
> I opened the issue a week ago.
> [mlpack/examples#63](https://github.com/mlpack/examples/issues/63)

Sorry @codeboy5 I didn't see the issue you opened. Should I close this now, since you've already completed it too.

**Comment by codeboy5** [comment]
If I was not done with the PR, I would have said to go on and merge this, But since I am completely done with it, maybe you can work on something similar.
I was thinking that squeezenet might be a good addition if you wanna take that up.

**Comment by codeboy5** [comment]
> > Hi @kartikdutt18.
> > I've already done the implementation but didn't add a PR due to the restructuring going on, was waiting for it to be completed.
> > I opened the issue a week ago.
> > [mlpack/examples#63](https://github.com/mlpack/examples/issues/63)
> 
> Sorry @codeboy5 I didn't see the issue you opened. Should I close this now, since you've already completed it too.

That would be great :) 
Sorry for the time you had to put in.

**Comment by prince776** [comment]
Ok so I will close it and work on squeezenet.

**Comment by codeboy5** [comment]
> Ok so I will close it and work on squeezenet.

Thanks, looking forward to your PR. :)

**Comment by prince776** [comment]
> That would be great :)
> Sorry for the time you had to put in.
It's ok, I should have seen issues/PRs related to it first :)

**Pull request closed without merging**
