### PR TITLE
Light fix of CI builds.

### PR DESCRIPTION
**Pull request by birm**
Of course, we'll probably want to actually _test_ this repository, rather than just see if it compiles. But for now, I'm just hoping that we can get CI into a working state.

### CODE REVIEW

**Comment by birm** [comment]
I'm leaving it like this for now -- this doesn't look like a CI configuration issue to me at least
```In file included from /usr/local/include/mlpack/methods/ann/layer/layer.hpp:41:0,

                 from /home/travis/build/mlpack/models/Kaggle/DigitRecognizer/src/DigitRecognizer.cpp:19:

/usr/local/include/mlpack/methods/ann/layer/weight_norm.hpp:68:76: error: expected ‘)’ before ‘>’ token

   WeightNorm(LayerTypes<CustomLayers...> layer = LayerTypes<CustomLayers...>());```

**Comment by kartikdutt18** [comment]
Hi @birm, I will try looking into it. Thanks.

**Comment by kartikdutt18** [comment]
Hi @birm, I tried to replicate the error but I wasn't successful in doing so. I was able to build mlpack as well as models project without any error. Any idea on how I should proceed?
Thanks.

**Comment by zoq** [comment]
> I'm leaving it like this for now -- this doesn't look like a CI configuration issue to me at least
> 
> ```
> 
>                  from /home/travis/build/mlpack/models/Kaggle/DigitRecognizer/src/DigitRecognizer.cpp:19:
> 
> /usr/local/include/mlpack/methods/ann/layer/weight_norm.hpp:68:76: error: expected ‘)’ before ‘>’ token
> 
>    WeightNorm(LayerTypes<CustomLayers...> layer = LayerTypes<CustomLayers...>());```
> ```

Using xenial instead of trusty might help, but we should look into the issue.

**Comment by birm** [comment]
That's interesting. I've the build error for trusty in  #46

**Comment by birm** [comment]
That's a lot of work (read: waiting for the CI results) for appveyor, considering that it'll hopefully quickly be replaced with a working vs test, but I didn't want to have a PR which only half fixed the CI tests. Hopefully squashing these messy commits will be enough.

**Comment by zoq** [comment]
> That's a lot of work (read: waiting for the CI results) for appveyor, considering that it'll hopefully quickly be replaced with a working vs test, but I didn't want to have a PR which only half fixed the CI tests. Hopefully squashing these messy commits will be enough.

Yeah, a lot of time between builds, but looks like it worked out in the end.

**Pull request merged**
