### PR TITLE
Remove travis configuration

### PR DESCRIPTION
**Pull request by rcurtin**
Similar to mlpack/mlpack#2416.

### CODE REVIEW

**Comment by kartikdutt18** [comment]
Hey @rcurtin, Sorry I missed the change here. It doesn't seem like we are running travis.yml here. Should that be the case?

**Comment by birm** [comment]
I guess so long as we have a travis file, it makes sense to fix it, but the fix to CI was done by @kartikdutt18 and merged in at https://github.com/mlpack/models/commit/c9054c0efe4437178dae6a931f513fe313319927#diff-ff1640c467ee5600fecc42cf57a6e2adR25

**Comment by rcurtin** [comment]
@kartikdutt18 it's true, but I figured it was good to change it anyway. :)

**Comment by kartikdutt18** [comment]
Ahh, makes sense. Thanks a lot for the clarification.

**Comment by rcurtin** [comment]
Actually, after some quick discussion in the video chat, it seems better to just remove the configuration entirely.  So I did that. :)

**Pull request merged**
