### PR TITLE
Documentation for models repo

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
### Requirements:
```
1. git+https://github.com/bashtage/sphinx-material.git
2. breathe = 4.30.0
3. exhale = 0.2.3
4. sphinx = 3.5.4
5. m2r2
```
All of the above mentioned packages are `pip3` installable 

```
doxygen = 1.9.1
```

### Steps to produce the documentation everytime there is a change 
```
cd doc
make html 
```
this should create a build folder in the doc directory in which you will find a html folder which will have all the files. 

### The main three files if you want to change anything are:
```
1. Doxyfile
2. conf.py
3. index.rst
```
All three files are inside `doc/source`

Do let me know if you need anything else.

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
@zoq here is the new PR. and thanks for taking it ahead. :D

**Comment by zoq** [comment]
Let me know if I should put this into a docker container or if you like to give this a shot.

**Comment by Aakash-kaushik** [comment]
> Let me know if I should put this into a docker container or if you like to give this a shot.

Please go ahead, because i don't really know docker that well so i would start small. Maybe not this time.

**Comment by Aakash-kaushik** [comment]
Keep open, we are going to look at this after https://github.com/mlpack/mlpack/pull/2990

**Comment by Aakash-kaushik** [comment]
https://user-images.githubusercontent.com/39410692/132120517-a6438b72-b897-4e45-973f-fd6d563eae9b.mp4

revival time :rocket: 
i am jus trying to include class hierarchy, file hierarchy and the on more thing below that to the side pane.

**Comment by Aakash-kaushik** [comment]
Update on the overall doc.
Let me know what you think.

https://user-images.githubusercontent.com/39410692/132128754-e2456672-f33c-43cd-a816-be22cddc36c0.mp4

**Comment by Aakash-kaushik** [comment]
https://gist.github.com/Aakash-kaushik/883f64cf5e148e542982add87ceaed64

Dockerfile gist to create image for building docs for models repo.

**Review by zoq — COMMENTED** [review]
@Aakash-kaushik what about we merge this, generate the documentation and open another PR for further modifications?

**Comment by Aakash-kaushik** [comment]
> @Aakash-kaushik what about we merge this, generate the documentation and open another PR for further modifications?

Sounds good to me.

**Review by zoq — APPROVED** [review]
This is super exciting.

**Review by shrit — APPROVED** [review]
@Aakash-kaushik Great work, thanks for putting this together.
Very excited to see the documentation get deployed, any thought where they are going to be published.
The only remaining part is the mlpack library one. :100:

**Comment by Aakash-kaushik** [comment]
> @Aakash-kaushik Great work, thanks for putting this together.
> Very excited to see the documentation get deployed, any thought where they are going to be published.
> The only remaining part is the mlpack library one. 💯

Yup, i would also be working on the mlpack docs.
And about the deployment @zoq or @rcurtin might be able to answer it better.

**Comment by zoq** [comment]
> > @Aakash-kaushik Great work, thanks for putting this together.
> > Very excited to see the documentation get deployed, any thought where they are going to be published.
> > The only remaining part is the mlpack library one. 100
> 
> Yup, i would also be working on the mlpack docs.
> And about the deployment @zoq or @rcurtin might be able to answer it better.

I think `mlpack.org/models/` or `models.mlpack.org` works. I'll setup the jenkins job later today.

**Comment by Aakash-kaushik** [comment]
> > > @Aakash-kaushik Great work, thanks for putting this together.
> > > Very excited to see the documentation get deployed, any thought where they are going to be published.
> > > The only remaining part is the mlpack library one. 100
> > 
> > 
> > Yup, i would also be working on the mlpack docs.
> > And about the deployment @zoq or @rcurtin might be able to answer it better.
> 
> I think `mlpack.org/models/` or `models.mlpack.org` works. I'll setup the jenkins job later today.

I am very excited for this too. ❤️🔥

**Comment by zoq** [comment]
:rocket:

**Comment by zoq** [comment]
Here we go: http://models.mlpack.org/docs/

**Comment by Aakash-kaushik** [comment]
> Here we go: http://models.mlpack.org/docs/

Thank you so much, btw i see some of the things that i would need to fix.
Also can we paste the link maybe on the repo description or somewhere so anyone going by knows that we have a documentation.

**Comment by zoq** [comment]
Absolutely, let's add a link to the top; I've also added a link to the section on the right side.

**Comment by kartikdutt18** [comment]
Love the website! thanks for putting this together!

**Pull request merged**
