### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by heisenbuug**
I have edited README.md so that work of this repository will be more clear and useful. I will also be adding more stuff about it like what all models it contain till now. Hope this will be helpful for everyone.

### CODE REVIEW

**Comment by zoq** [comment]
This is definitely helpful, looking forward to see this finished.

**Comment by heisenbuug** [comment]
@zoq Do you have any specifics in mind for this or any suggestions?

**Comment by zoq** [comment]
I like the existing ideas:

```
* Step by step instructions on how to use the trained model
* A standard and simple way to download the trained model
* References to any other applicable docs or arxiv papers the model is based on
```
we can start by filling in some details.

**Comment by heisenbuug** [comment]
@zoq while talking about VAE, should I also create a page which introduces the concept of VAE's or are we assuming that people already know that and we just need to tell them how to use our code...

**Comment by rcurtin** [comment]
Hey @heisenbuug, thanks for writing this up.  I meant to respond to this a long time ago but I forgot to.  If you're still interested in working on it (I know it has been many months...) I would be happy to help out.  For VAE, I think that we can assume people know what they are, although it may not hurt to include a link to Wikipedia or some other resource for people who are not familiar.  No need to write something big up.

**Comment by heisenbuug** [comment]
@rcurtin Hey I am really sorry, I lost track of this issue and never saw your reply till date. I still want to work on Model Zoo but I think this issue is of no use now. But I think we should add some more models to the zoo and also some improvements to readme files. Rather than explaining the concepts which as you said they can look up on wiki we can explain how to implement the code using MLPack i.e. some tutorials. Also what I mainly want to do is to add more models so that more number of users can take advantage of this Model Zoo

**Comment by heisenbuug** [comment]
> Hey @heisenbuug, thanks for writing this up. I meant to respond to this a long time ago but I forgot to. If you're still interested in working on it (I know it has been many months...) I would be happy to help out. For VAE, I think that we can assume people know what they are, although it may not hurt to include a link to Wikipedia or some other resource for people who are not familiar. No need to write something big up.

Heyy @rcurtin I know you might be busy but can we start a discussion about adding more models?

**Comment by rcurtin** [comment]
Hey @heisenbuug, that's a fair point.  Do you think we should close this PR then?

I definitely agree that we should expand the model zoo, and perhaps adding details about each model in a directory-specific readme is the better way to go. :+1:

**Comment by heisenbuug** [comment]
@rcurtin I have opened a new issue regarding this, we can discuss more [there](https://github.com/mlpack/models/issues/54)

**Comment by rcurtin** [comment]
@heisenbuug thanks---that sounds good to me.  I'll go ahead and close this then. :+1:

**Pull request closed without merging**
