### PR TITLE
Add modular vgg16 network

### PR DESCRIPTION
**Pull request by adithya-tp**
Migrating pull request [#62](https://github.com/mlpack/examples/pull/62) from mlpack/examples to here. Thanks for the heads-up @favre49. 

Additionally I plan on extending this implementation to include vgg19 as well. This is still a work in progress, and please feel free to reach out with suggestions :)

### CODE REVIEW

**Comment by birm** [comment]
Thanks for the migrated PR! Can you take a moment to fix the merge conflict, and to move this to a top level dir such as "VGG16" (though I'm open to explanation for the filepath you've chosen for this)

**Comment by adithya-tp** [comment]
Hey birm! Its nice talking to you again. I'm in the middle of my university finals right now, which is why I couldn't respond to your comment sooner.

There's obviously more work to be done on this PR, and I'll be able to work on it after a couple weeks. Thought I'd leave an update on things, that's all :)

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by adithya-tp** [comment]
Keep open.

**Pull request closed without merging**
