### PR TITLE
added gan

### PR DESCRIPTION
**Pull request by Soonmok**
Added examples of gan network on mnist dataset.
Added examples of Generating image from gan generator.

### CODE REVIEW

**Comment by Soonmok** [comment]
Change to use ensmallen to pass build test

**Comment by zoq** [comment]
There is an open PR https://github.com/mlpack/models/pull/18, which should fix the build issue, I'll see if I can fix the error in the next days.

**Comment by zoq** [comment]
Thanks to @rcurtin the build issue is fixed, see https://github.com/mlpack/models/pull/18 for more information.

**Comment by Soonmok** [comment]
I will

**Pull request closed without merging**
