### PR TITLE
Ctest Fix

### PR DESCRIPTION
**Pull request by Aakash-kaushik**
We removed ctest couple of days ago because it was reporting failed test cases as passed, this is a fix so it reports tests corectly.

So I have a obvious failing test case in this PR, just to check if it detects and reports the failing tests properly and if so I am just going to remove the extra test i added and this should be good to go then. 

Btw i just found out that if you are not nervous while debugging something it helps a lot in actually concurring the problem. :D
~ Quotes by Aakash :rofl:

### CODE REVIEW

**Comment by Aakash-kaushik** [comment]
Leaving a comment to show that this actually works and fixing the obviously wrong test case.
Output from CI
```bash
Run tests via ctest

View raw log

/home/vsts/work/1/s/tests/utils_tests.cpp:23: FAILED:
  REQUIRE( 0 == 1 )

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed


      Start 19: CheckSumTest
19/23 Test #19: CheckSumTest .............................   Passed    0.21 sec
      Start 20: PathExistsTest
20/23 Test #20: PathExistsTest ...........................   Passed    0.01 sec
      Start 21: RemoveFileTest
21/23 Test #21: RemoveFileTest ...........................   Passed    0.01 sec
      Start 22: ExtractFilesTest
22/23 Test #22: ExtractFilesTest .........................   Passed    0.40 sec
      Start 23: CurlDownloadTest
23/23 Test #23: CurlDownloadTest .........................   Passed    0.21 sec

96% tests passed, 1 tests failed out of 23

Total Test time (real) = 2830.49 sec

The following tests FAILED:
	 18 - DownloadFileTest (Failed)
Errors while running CTest
##[error]Bash exited with code '8'
```

**Review by zoq — COMMENTED** [review]
Nice, looks like now we have to fix the failing windows test.

**Comment by Aakash-kaushik** [comment]
So one of the errors in windows is this: 
```bash
-------------------------------------------------------------------------------
PreTrainedResNetModel152Test
-------------------------------------------------------------------------------
D:\a\1\s\tests\ffn_model_tests.cpp(190)
...............................................................................

D:\a\1\s\tests\ffn_model_tests.cpp(190): FAILED:
due to unexpected exception with message:
  bad allocation
```

and the other one is this:
```bash
-------------------------------------------------------------------------------
ResNet152ModelTest
-------------------------------------------------------------------------------
D:\a\1\s\tests\ffn_model_tests.cpp(142)
...............................................................................

D:\a\1\s\tests\ffn_model_tests.cpp(142): FAILED:
due to unexpected exception with message:
  bad allocation
```

Seems like something in the resnet152 fails on windows specifically but does pass on other OS, I might check the armadillo version maybe.

**Comment by Aakash-kaushik** [comment]
> So one of the errors in windows is this:
> 
> ```shell
> -------------------------------------------------------------------------------
> PreTrainedResNetModel152Test
> -------------------------------------------------------------------------------
> D:\a\1\s\tests\ffn_model_tests.cpp(190)
> ...............................................................................
> 
> D:\a\1\s\tests\ffn_model_tests.cpp(190): FAILED:
> due to unexpected exception with message:
>   bad allocation
> ```
> 
> and the other one is this:
> 
> ```shell
> -------------------------------------------------------------------------------
> ResNet152ModelTest
> -------------------------------------------------------------------------------
> D:\a\1\s\tests\ffn_model_tests.cpp(142)
> ...............................................................................
> 
> D:\a\1\s\tests\ffn_model_tests.cpp(142): FAILED:
> due to unexpected exception with message:
>   bad allocation
> ```
> 
> Seems like something in the resnet152 fails on windows specifically but does pass on other OS, I might check the armadillo version maybe.
> 
> Also it's just hard for me to emulate these locally, i don't have my windows setup and i don't have a huge experience with VS code and build systems in windows.

@zoq do you think it is just running out of memory ?

**Comment by Aakash-kaushik** [comment]
these same tests were failing in the mobilenet v1 PR too: https://dev.azure.com/mlpack/mlpack/_build/results?buildId=6986&view=logs&j=9bb75cf0-500a-52c4-dbba-9c305edd1534&t=8c73cb50-6662-5f10-51d0-fd7f37efe07e
But just wasn't reported because of the issue.

**Comment by Aakash-kaushik** [comment]
I kinda suspect memory usage, @zoq if you have good amount of ram can you just locally run this on your windows system and let me know if it runs successfully ?
```c++
#include "models/models/resnet/resnet.hpp"
#include <armadillo>

using namespace mlpack::models;
using namespace mlpack::ann;

int main()
{
  mlpack::Log::Info.ignoreInput = false;
  ResNet152 resnet(3, 224, 224, true, true);
  arma::mat input(224 * 224 * 3, 1), output;
  resnet.GetModel().Predict(input, output);
  std::cout << output.n_rows << std::endl;
  return 0;
}
```

**Comment by zoq** [comment]
> I kinda suspect memory usage, @zoq if you have good amount of ram can you just locally run this on your windows system and let me know if it runs successfully ?
> 
> ```c++
> #include "models/models/resnet/resnet.hpp"
> #include <armadillo>
> 
> using namespace mlpack::models;
> using namespace mlpack::ann;
> 
> int main()
> {
>   mlpack::Log::Info.ignoreInput = false;
>   ResNet152 resnet(3, 224, 224, true, true);
>   arma::mat input(224 * 224 * 3, 1), output;
>   resnet.GetModel().Predict(input, output);
>   std::cout << output.n_rows << std::endl;
>   return 0;
> }
> ```

Yes, works fine with more memory, so let's skip the resnet tests on Windows, I might be able to add a Windows node to the jenkins installation at some point.

**Comment by Aakash-kaushik** [comment]
Seems ok, i guess.
Btw can we somehow remember to test it again after the vtable PR? 
I hope that might reduce memory usage. 🤞

**Comment by zoq** [comment]
> Seems ok, i guess.
> Btw can we somehow remember to test it again after the vtable PR?
> I hope that might reduce memory usage.

Yes, pretty sure once the vtable transition is done this is solved as well.

**Comment by Aakash-kaushik** [comment]
> > Seems ok, i guess.
> > Btw can we somehow remember to test it again after the vtable PR?
> > I hope that might reduce memory usage.
> 
> Yes, pretty sure once the vtable transition is done this is solved as well.

With the final commit all the builds should come green, so this should be good to go too. I might go and headbang with the depthwise PR then.

**Review by zoq — APPROVED** [review]
Ready to go from my side, great work.

**Comment by zoq** [comment]
Thanks for getting this done.

**Pull request merged**
