### PR TITLE
Le net

### PR DESCRIPTION
**Pull request by s1998**
- [x] Add make file

### CODE REVIEW

**Comment by s1998** [comment]
Results for 50 iterations

> Reading data ...
Data loaded : 
Splitting done
Model made and optimizer done.
0 - accuracy: train = 19.2589%, valid = 19.631%
1 - accuracy: train = 29.8393%, valid = 29.6429%
2 - accuracy: train = 42.2679%, valid = 42.1548%
3 - accuracy: train = 46.6875%, valid = 47.0595%
4 - accuracy: train = 54.4226%, valid = 54.381%
5 - accuracy: train = 64.6607%, valid = 64.131%
6 - accuracy: train = 68.4702%, valid = 68.3571%
7 - accuracy: train = 73.3244%, valid = 72.8333%
8 - accuracy: train = 77.9196%, valid = 77.369%
9 - accuracy: train = 76.8214%, valid = 76.0238%
10 - accuracy: train = 82.3869%, valid = 81.6786%
11 - accuracy: train = 79.2292%, valid = 78.6786%
12 - accuracy: train = 79.6875%, valid = 79.5833%
13 - accuracy: train = 85.8214%, valid = 85%
14 - accuracy: train = 84.0863%, valid = 84%
15 - accuracy: train = 83.3631%, valid = 82.2976%
16 - accuracy: train = 84.4792%, valid = 83.7619%
17 - accuracy: train = 82.8244%, valid = 82.7143%
18 - accuracy: train = 86.2738%, valid = 86.6071%
19 - accuracy: train = 86.0625%, valid = 86.3452%
20 - accuracy: train = 86.9315%, valid = 86.4405%
21 - accuracy: train = 78.8958%, valid = 78.5714%
22 - accuracy: train = 86.4554%, valid = 85.7381%
23 - accuracy: train = 87.0655%, valid = 86.8095%
24 - accuracy: train = 87.1994%, valid = 87.0952%
25 - accuracy: train = 86.0774%, valid = 86.2024%
26 - accuracy: train = 88.3304%, valid = 88%
27 - accuracy: train = 83.5982%, valid = 82.869%
28 - accuracy: train = 89.1518%, valid = 88.369%
29 - accuracy: train = 82.4821%, valid = 82.8095%
30 - accuracy: train = 88.7292%, valid = 88.25%
31 - accuracy: train = 89.7083%, valid = 89.4643%
32 - accuracy: train = 86.1756%, valid = 85.6548%
33 - accuracy: train = 87.997%, valid = 87.7262%
34 - accuracy: train = 87.7054%, valid = 86.9643%
35 - accuracy: train = 88.131%, valid = 87.5476%
36 - accuracy: train = 89.9375%, valid = 89.4405%
37 - accuracy: train = 85.7232%, valid = 85.2024%
38 - accuracy: train = 86.3542%, valid = 85.9762%
39 - accuracy: train = 87.5536%, valid = 87.2262%
40 - accuracy: train = 89.2381%, valid = 89.1071%
41 - accuracy: train = 89.006%, valid = 88.8214%
42 - accuracy: train = 90.6637%, valid = 90.5357%
43 - accuracy: train = 89.8542%, valid = 89.3214%
44 - accuracy: train = 87.3304%, valid = 86.8214%
45 - accuracy: train = 88.9435%, valid = 88.1071%
46 - accuracy: train = 88.7262%, valid = 88.5476%
47 - accuracy: train = 90.6756%, valid = 89.9643%
48 - accuracy: train = 90.0625%, valid = 89.3452%
49 - accuracy: train = 90.6488%, valid = 90.2143%
50 - accuracy: train = 89.7173%, valid = 89.4167%

**Comment by rcurtin** [comment]
Did you tune the step size?  It looks like it might be learning too quickly.  (I am not sure, since we only have training accuracy not the actual objective function output.)  In any case, looks pretty good so far.  I'll review the code when I have a chance.

**Comment by s1998** [comment]
@rcurtin The step size is set as 5e-3 currently (no of cycles = 20).

 I tried with 5e-4 and it reached 92% in 70 cycles.

**Comment by zoq** [comment]
I think it would make sense if we predict the test set during the training process, e.g. every 10 iterations, that would give us some more information.

**Comment by s1998** [comment]
@zoq  @rcurtin  The dataset available originally as MNIST and the kaggle have different test sizes 
(kaggle train : 48000, test : 28000; original train : 60000, test : 10000). So should I make similar changes in the FFN too ?

**Comment by zoq** [comment]
I see, I think for this example we could use the original one, this basically an example so, I think it make sense to provide different possibilities.

**Comment by rcurtin** [comment]
If we are going to not use the Kaggle dataset here, I think we should move the model to its own directory; how about `LeNet_MNIST` or something?

**Comment by s1998** [comment]
@rcurtin  I will make the necessary changes ASAP.

**Comment by s1998** [comment]
Closing this since pr #12 gives better performance using a CNN.

**Pull request closed without merging**
